"use client";

import React from "react";
import { Sparkles } from "lucide-react";
import { Project } from "@/types/project";

export function BrandSummary({ project }: { project: Project | null }) {
  return (
    <div className="bg-indigo-50/50 rounded-xl border border-indigo-100 p-6 h-full flex flex-col justify-between relative overflow-hidden">
      <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none">
        <Sparkles className="w-24 h-24 text-indigo-600" />
      </div>
      <div>
        <h3 className="font-bold text-slate-900 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-indigo-600" />
          AI Brand Summary
        </h3>
        <p className="mt-4 text-sm font-medium text-slate-700 leading-relaxed relative z-10">
          {project?.brand_name || "Acme Solutions"} is an AI-powered growth platform built for ambitious founders and marketing teams. The brand combines innovation with clarity—delivering data-driven insights, automation, and measurable impact. Its voice is confident, professional, and forward-thinking, with a focus on helping businesses scale smarter and faster.
        </p>
      </div>
      
      <div className="mt-6 flex items-center gap-2">
        <span className="px-2.5 py-1 rounded-md bg-indigo-100 text-indigo-700 text-[10px] font-bold flex items-center gap-1">
          <Sparkles className="w-3 h-3" /> Generated by SoloSpider AI
        </span>
      </div>
    </div>
  );
}
